__merge__: /src/api/comp_method.yaml

name: ecdf_qnorm
label: ecdf_qnorm
summary: Data normalization based on ecdf and tiedranks.

# A multi-line description of how this component works (required). Used
# when rendering reference documentation.
description: |
  ecdfQnorm is Data normalization based on ecdf and tiedranks.
  we normalize the data ...
  more text ...
#references:
#  doi: 10.1016/j.cell.2019.05.006 # this is the pyliger librery

#links:
##  documentation: https://github.com/hofreelab/ecdfQnorm/#readme
##  repository: https://github.com/hofreelab/ecdfQnorm/
#  documentation: https://github.com/welch-lab/pyliger # for test
#  repository: https://github.com/welch-lab/pyliger # for test



# Metadata for your component
info:
  # Which normalisation method this component prefers to use (required).
  preferred_normalization: log_cp10k

# Component-specific parameters (optional)
arguments:
   - name: "--batch_key"
     type: "string"
     default: "batch"
     description: the name of the batch key in the input data


resources:
  # The script of your component (required)
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
  # Additional resources your script needs (optional)
  # - type: file
  #   path: weights.pt

engines:
  - type: docker
    image: openproblems/base_python:1
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
       - type: python
         packages:
           - scanpy
           - tqdm
           - scipy
           - numpy


runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
